# Generated by Django 4.1.1 on 2022-09-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Automobilio_modelis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marke", models.CharField(max_length=15, verbose_name="Marke")),
                ("modelis", models.CharField(max_length=15, verbose_name="Modelis")),
            ],
            options={
                "verbose_name": "Automobilio_modelis",
                "verbose_name_plural": "Automobilio_modeliai",
            },
        ),
        migrations.CreateModel(
            name="Automobilis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valst_nr",
                    models.CharField(max_length=6, verbose_name="Valstybinis nr."),
                ),
                ("vin", models.CharField(max_length=17, verbose_name="VIN kodas")),
                ("klientas", models.CharField(max_length=30, verbose_name="Klientas")),
                (
                    "auto_modelis_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="autoservice.automobilio_modelis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Automobilis",
                "verbose_name_plural": "Automobiliai",
            },
        ),
        migrations.CreateModel(
            name="Paslauga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pavadinimas",
                    models.CharField(max_length=50, verbose_name="Pavadinimas"),
                ),
                ("kaina", models.FloatField(verbose_name="Kaina")),
            ],
            options={
                "verbose_name": "Paslauga",
                "verbose_name_plural": "Paslaugos",
            },
        ),
        migrations.CreateModel(
            name="Uzsakymas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(blank=True, verbose_name="Data")),
                ("suma", models.FloatField(verbose_name="Suma")),
                (
                    "automobilis_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="autoservice.automobilis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uzsakymas",
                "verbose_name_plural": "Uzsakymai",
            },
        ),
        migrations.CreateModel(
            name="Uzsakymo_eilute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kiekis", models.IntegerField(verbose_name="Kiekis")),
                ("kaina", models.FloatField(verbose_name="Kaina")),
                (
                    "paslauga_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="autoservice.paslauga",
                    ),
                ),
                (
                    "uzsakymas_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="autoservice.uzsakymas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uzsakymo_eilute",
                "verbose_name_plural": "Uzsakymo_eilutes",
            },
        ),
    ]
